- name: Download nodejs repository setup script
  get_url:
    url: "https://raw.githubusercontent.com/nodesource/distributions/master/deb/setup_{{ node_version }}"
    dest: "/tmp/nodejs_setup"
    mode: 0577

- name: Run the nodejs setup script
  command: "/tmp/nodejs_setup"

- name: Install necessary packages
  apt:
    name: nodejs
